-- Add SEO + image meta fields to BlogPost for Blog Manager

ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "seoTitle" TEXT;
ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "seoDescription" TEXT;
ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "canonicalUrl" TEXT;
ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "focusKeyword" TEXT;
ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "robotsIndex" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "robotsFollow" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "imageAlt" TEXT;
ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "imageTitle" TEXT;
ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "imageCaption" TEXT;
ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "imageFileName" TEXT;

ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "extraSchemaJson" JSONB;

