-- Align fleet pricing columns with admin/API usage
ALTER TABLE "FleetVehicle" ADD COLUMN IF NOT EXISTS "basePrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "FleetVehicle" ADD COLUMN IF NOT EXISTS "baseDistanceKm" DOUBLE PRECISION NOT NULL DEFAULT 17;
ALTER TABLE "FleetVehicle" ADD COLUMN IF NOT EXISTS "extraKmRate" DOUBLE PRECISION NOT NULL DEFAULT 0;

UPDATE "FleetVehicle"
SET "extraKmRate" = "pricePerKm"
WHERE ("extraKmRate" = 0 OR "extraKmRate" IS NULL) AND "pricePerKm" > 0;

ALTER TABLE "AppFleetVehicle" ADD COLUMN IF NOT EXISTS "baseDistanceKm" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "AppFleetVehicle" ADD COLUMN IF NOT EXISTS "extraKmRate" DOUBLE PRECISION NOT NULL DEFAULT 0;
